default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: db/development_instagramm_new

test:
  <<: *default
  database: db/test_instagramm_new

production:
  <<: *default
  database: db/production_instagramm_new
